### ISSUE TITLE
left hand nil error

### ISSUE THREAD

**Issue by Lichery** [RagedUnicorn/wow-gearmenu#1]
There is no check of the presence of the item in the left hand

Click "Offhand" in Options menu\Quick Change
![bandicam 2018-02-08 01-16-21-463](https://user-images.githubusercontent.com/24303693/35944541-da1a5a66-0c6d-11e8-9391-91748ccf105e.jpg)

**Comment by Lichery** [comment]
fix this error:
343 line must be 
if itemQuality and itemQuality >= GearMenuOptions.filterItemQuality then

**Comment by RagedUnicorn** [comment]
Hi @Lichery,

thanks for the hint you're absolutely right this was an oversight when I implemented the feature for checking for the itemquality.

There is now a check in place that checks if any information can be retrieved from the item in the current slot. If not it is assumed that there is no item in that slot and it gets skipped.

Thanks for your contribution
