### ISSUE TITLE
Suggestion - Add ranged weapon slot

### ISSUE THREAD

**Issue by mooblia** [RagedUnicorn/wow-gearmenu#13]
Hey there, first of all great add-on! Currently every slot except the ranged weapon slot can be put on the gear bar, is it possible to add that for completeness?

Thanks a bunch. :)

**Comment by RagedUnicorn** [comment]
Hi,

Almost suspected someone would ask for it :) Yeah I will add it once I find some time.

Cheers,
RagedUnicorn

**Comment by RagedUnicorn** [comment]
Hi @mooblia,

As promised I included the slot. You can find it in the newest release [1.2.1](https://github.com/RagedUnicorn/wow-gearmenu/releases/tag/v1.2.1)

Cheers,
RagedUnicorn
