### ISSUE TITLE
Size

### ISSUE THREAD

**Issue by Mugizst** [RagedUnicorn/wow-gearmenu#3]
There doesn't seem to be a way to resize the bar at all, and the lower right arrow when the addon is unlocked only moves the menu as opposed to scaling it (TrinketMenu uses this arrow for scaling and I assume the same function was intended here).

**Comment by playerwtf** [comment]
Hi that is correct I saw this in the old TrinketMenu as well but I just didn't implement scaling as of right now. I might consider adding it at some point but as of right now it is working as intended.

**Comment by RagedUnicorn** [comment]
Hi that is correct I saw this in the old TrinketMenu as well but I just didn't implement scaling as of right now. I might consider adding it at some point but as of right now it is working as intended.
