### ISSUE TITLE
Cooldowns overlapping with modui

### ISSUE THREAD

**Issue by nono234** [RagedUnicorn/wow-gearmenu#4]
https://imgur.com/a/GOUZL this happens with Omnicc aswell.

**Comment by RagedUnicorn** [comment]
Hi nono234,

while I dislike that addons such as Omnicc and modui just hook(CooldownFrame_SetTimer) into everything they can find and are causing this there is an easy fix for that.

Use /gm opt to open the options menu
Switch to the general menu
Deactivate "Show Cooldowns"

From now on gearmenu no longer shows cooldowns but other addons should still be able to show the cooldown.

Regards,
RagedUnicorn
