### ISSUE TITLE
how do i get wand to work with gearmenu

### ISSUE THREAD

**Issue by bballaz** [RagedUnicorn/wow-gearmenu#5]
i have seen videos of people using gearmenu for wands. how do i get this to work

**Comment by RagedUnicorn** [comment]
Hi I'm not aware of such a video. If you can still find it please post it here but I guess they used a different addon. Gearmenu is intended for slots that have **usable** items. Meaning I can click them and they do something additionaly. I'm currently not aware of any wands that have such an usable effect. Thats why this slot is not supported by Gearmenu. It is however possible to add support for that slot.

If you can explain your case why you would need this I will consider it.

**Comment by vakos1** [comment]
I would like this for Blackwing Lair - all of the mobs that are vulnerable to a specific school of magic and Chromaggus require me to swap wands frequently in order to hit them.

**Comment by RagedUnicorn** [comment]
Hi @EyeOfTheBeast,

This ticket is very old and wands are fully supported in the meantime. However Blizzard prevents addons from automatically switching weapons while in combat. In your case you would probably still need to switch the wand manually.

Cheers,
RagedUnicorn
