### ISSUE TITLE
GearMenu 1.0.2 not working ?

### ISSUE THREAD

**Issue by Wushengg** [RagedUnicorn/wow-gearmenu#6]
I downloaded the release version for 1.0.2 and when I load the game I get this error https://imgur.com/2ARG38W

Nothing is working except for the /gm opt command but it looks like this https://imgur.com/qjFTriz

I tried downloading 1.0.1 and its working just fine. It shouldn't be an addon compatibility issue since I've tried disabling everything except gearmenu.

**Comment by RagedUnicorn** [comment]
Hi sorry for taking so long to answer. There is indeed an issue with that version. I was able to reporduce the issue. Made a mistake during packaging of the release. The translation is not getting packaged causing the error you see.

I will fix this as soon as possible

**Comment by RagedUnicorn** [comment]
Hi got this fixed in release 1.0.3

Regards,
RagedUnicorn
