### ISSUE TITLE
Keybinding not available

### ISSUE THREAD

**Issue by DisMisaL** [RagedUnicorn/wow-gearmenu#8]
With latest release, there is no GearMenu options in Key Bindings menu.

**Comment by phendrome** [comment]
True. Cannot be seen in the key bindings menu at all. Not visible.

**Comment by Wushengg** [comment]
The file "Bindings.xml" is missing from 1.0.3 and 1.0.2. An easy way you can fix the issue yourselves is by downloading the 1.0.1 release and taking the bindings file and put it with your newer version.

**Comment by RagedUnicorn** [comment]
Hi guys,

I was just able to reproduce this. Looks like another issue I overlooked when the Addon is packaged for release. `Bindings.xml` wasn't packed properly. I will fix this in the next release.

Regards,
RagedUnicorn

**Comment by RagedUnicorn** [comment]
Hi again,

This is now fixed in the [v1.1.0](https://github.com/RagedUnicorn/wow-gearmenu/releases/tag/v1.1.0) release. Let me know if you stumble on any other issues

Regards,
Ragedunicorn
